version: '3.5'

services:
    database:
        image: postgres:11-alpine
        ports: [5432]
        environment:
            POSTGRES_USER: skunky
            POSTGRES_PASSWORD: teoficom5
            POSTGRES_DB: skunkydb
    redis:
        image: redis:5.0.7-alpine
        ports: [6379]